"""Memory-bounded colored point-cloud and MeshLab-project export helpers."""

from __future__ import annotations

import math
import os
import tempfile
import xml.etree.ElementTree as element_tree
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np


VERTEX_DTYPE = np.dtype(
    [
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("red", "u1"),
        ("green", "u1"),
        ("blue", "u1"),
    ]
)


@dataclass(frozen=True)
class PointLayer:
    """One MeshLab-ready sampled point cloud and its exact source count."""

    path: Path
    label: str
    color_rgb: tuple[int, int, int]
    source_voxel_count: int
    sampled_point_count: int
    sampling_stride: int


def _validate_color(color_rgb: Sequence[int]) -> tuple[int, int, int]:
    color = tuple(int(value) for value in color_rgb)
    if len(color) != 3 or any(value < 0 or value > 255 for value in color):
        raise ValueError("color_rgb must contain three integers in [0, 255]")
    return color


def sampled_vertices_from_mask(
    mask_zyx: np.ndarray,
    *,
    offset_zyx: Sequence[int] = (0, 0, 0),
    native_voxels_per_cell: int = 1,
    color_rgb: Sequence[int],
    max_points: int,
    sampling_stride: int | None = None,
) -> tuple[np.ndarray, int, int]:
    """Sample a ZYX mask deterministically into colored XYZ point vertices.

    The quantitative metric must use the complete mask. This function makes a
    display-only point sample, scanning one Z plane at a time so it never
    builds an all-foreground-coordinate array for a multi-million-voxel mask.
    """

    mask = np.asarray(mask_zyx, dtype=bool)
    if mask.ndim != 3:
        raise ValueError(f"mask_zyx must be 3D, got {mask.ndim}D")
    offset = tuple(int(value) for value in offset_zyx)
    if len(offset) != 3:
        raise ValueError("offset_zyx must contain exactly three values")
    if native_voxels_per_cell < 1:
        raise ValueError("native_voxels_per_cell must be >= 1")
    if max_points < 1:
        raise ValueError("max_points must be >= 1")
    color = _validate_color(color_rgb)

    source_count = int(np.count_nonzero(mask))
    if source_count == 0:
        return np.empty(0, dtype=VERTEX_DTYPE), 0, 1
    if sampling_stride is not None:
        if int(sampling_stride) != sampling_stride or sampling_stride < 1:
            raise ValueError("sampling_stride must be a positive integer when supplied")
        stride = int(sampling_stride)
    else:
        stride = max(1, math.ceil(source_count / max_points))
    sample_count = (source_count - 1) // stride + 1
    vertices = np.empty(sample_count, dtype=VERTEX_DTYPE)
    rank_start = 0
    write_start = 0
    for local_z in range(mask.shape[0]):
        local_y, local_x = np.nonzero(mask[local_z])
        count = len(local_x)
        if not count:
            continue
        ranks = np.arange(rank_start, rank_start + count, dtype=np.int64)
        keep = ranks % stride == 0
        selected_y = local_y[keep]
        selected_x = local_x[keep]
        selected_count = len(selected_x)
        destination = slice(write_start, write_start + selected_count)
        vertices["x"][destination] = (
            selected_x.astype(np.float32) + offset[2]
        ) * native_voxels_per_cell
        vertices["y"][destination] = (
            selected_y.astype(np.float32) + offset[1]
        ) * native_voxels_per_cell
        vertices["z"][destination] = (local_z + offset[0]) * native_voxels_per_cell
        vertices["red"][destination] = color[0]
        vertices["green"][destination] = color[1]
        vertices["blue"][destination] = color[2]
        rank_start += count
        write_start += selected_count
    if write_start != sample_count:
        raise RuntimeError("deterministic point sampling count mismatch")
    return vertices, source_count, stride


def write_colored_points_ply(
    path: str | Path,
    vertices: np.ndarray,
    *,
    comments: Iterable[str] = (),
) -> Path:
    """Atomically write a binary little-endian RGB point-cloud PLY."""

    array = np.asarray(vertices)
    if array.dtype != VERTEX_DTYPE or array.ndim != 1:
        raise ValueError("vertices must be a one-dimensional VERTEX_DTYPE array")
    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    sanitized = [str(value).replace("\n", " ").replace("\r", " ") for value in comments]
    header = "\n".join(
        [
            "ply",
            "format binary_little_endian 1.0",
            "comment generated by Aman_Scripts/tif2stl/meshlab_export.py",
            *(f"comment {value}" for value in sanitized),
            f"element vertex {len(array)}",
            "property float x",
            "property float y",
            "property float z",
            "property uchar red",
            "property uchar green",
            "property uchar blue",
            "end_header",
            "",
        ]
    ).encode("ascii")
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_name = handle.name
            handle.write(header)
            handle.write(np.ascontiguousarray(array).tobytes())
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, destination)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)
    return destination


def read_colored_points_ply(path: str | Path) -> np.ndarray:
    """Read a colored point PLY produced by :func:`write_colored_points_ply`.

    This intentionally accepts the small, documented subset that this module
    writes: binary little-endian vertex-only PLY files with XYZ and RGB fields.
    Keeping the parser narrow makes direct-view assembly deterministic and
    avoids treating an arbitrary mesh file as trusted binary data.
    """

    source = Path(path).expanduser().resolve()
    with source.open("rb") as handle:
        first_line = handle.readline()
        if first_line != b"ply\n":
            raise ValueError(f"not a PLY file written by this exporter: {source}")
        vertex_count: int | None = None
        binary_little_endian = False
        while True:
            line = handle.readline()
            if not line:
                raise ValueError(f"unterminated PLY header: {source}")
            text = line.decode("ascii", errors="strict").strip()
            if text == "format binary_little_endian 1.0":
                binary_little_endian = True
            elif text.startswith("element vertex "):
                try:
                    vertex_count = int(text.rsplit(" ", 1)[1])
                except ValueError as error:
                    raise ValueError(f"invalid vertex count in {source}") from error
            elif text == "end_header":
                break
        if not binary_little_endian or vertex_count is None or vertex_count < 0:
            raise ValueError(f"unsupported colored-point PLY header: {source}")
        vertices = np.fromfile(handle, dtype=VERTEX_DTYPE, count=vertex_count)
    if len(vertices) != vertex_count:
        raise ValueError(
            f"truncated PLY vertex data: expected {vertex_count}, found {len(vertices)} in {source}"
        )
    return vertices


def merge_colored_points_ply(
    destination: str | Path,
    sources: Sequence[str | Path],
    *,
    comments: Iterable[str] = (),
) -> tuple[Path, int]:
    """Merge compatible colored PLY evidence layers into one direct-view PLY."""

    source_paths = tuple(Path(path).expanduser().resolve() for path in sources)
    if not source_paths:
        raise ValueError("at least one source PLY is required")
    arrays = [read_colored_points_ply(path) for path in source_paths]
    merged = np.concatenate(arrays) if len(arrays) > 1 else arrays[0]
    path = write_colored_points_ply(destination, merged, comments=comments)
    return path, len(merged)


def export_mask_layer(
    mask_zyx: np.ndarray,
    *,
    destination: str | Path,
    label: str,
    color_rgb: Sequence[int],
    offset_zyx: Sequence[int],
    native_voxels_per_cell: int,
    max_points: int,
    metric_note: str,
    sampling_stride: int | None = None,
) -> PointLayer:
    """Create one display-sampled PLY while retaining exact source count."""

    vertices, source_count, stride = sampled_vertices_from_mask(
        mask_zyx,
        offset_zyx=offset_zyx,
        native_voxels_per_cell=native_voxels_per_cell,
        color_rgb=color_rgb,
        max_points=max_points,
        sampling_stride=sampling_stride,
    )
    path = write_colored_points_ply(
        destination,
        vertices,
        comments=(
            label,
            metric_note,
            f"exact source voxels {source_count}",
            f"display points {len(vertices)} sampled every {stride} occupied voxels",
            "coordinates are CT native XYZ voxel centers",
        ),
    )
    return PointLayer(
        path=path,
        label=label,
        color_rgb=_validate_color(color_rgb),
        source_voxel_count=source_count,
        sampled_point_count=len(vertices),
        sampling_stride=stride,
    )


def write_meshlab_project(
    path: str | Path,
    layers: Sequence[PointLayer],
) -> Path:
    """Write a MeshLab .mlp project with human-readable metric layer names."""

    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    project = element_tree.Element("MeshLabProject")
    mesh_group = element_tree.SubElement(project, "MeshGroup")
    for layer in layers:
        mesh = element_tree.SubElement(
            mesh_group,
            "MLMesh",
            {
                "label": layer.label,
                "filename": layer.path.name,
            },
        )
        matrix = element_tree.SubElement(mesh, "MLMatrix44")
        matrix.text = "\n1 0 0 0\n0 1 0 0\n0 0 1 0\n0 0 0 1\n"
    element_tree.SubElement(project, "RasterGroup")
    body = element_tree.tostring(project, encoding="unicode")
    destination.write_text(
        "<!DOCTYPE MeshLabDocument>\n" + body + "\n",
        encoding="utf-8",
    )
    return destination
