#!/usr/bin/env python3
"""Compare every 0.5-STL strut directly with native raw-TIFF material.

The output preserves the registered lattice JSON schema and augments every
strut with endpoints, a nullable binary error candidate, and numeric evidence.
No visualization is generated by this command.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from Components.paths import data_path, output_path  # noqa: E402
from Components.reporting import write_csv, write_json  # noqa: E402
from Components.strut_pipeline import compare_stl_to_tiff_struts  # noqa: E402


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    missing = data_path("missing_struts")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stl", default=str(missing / "stls" / "0.5.stl"))
    parser.add_argument(
        "--complete-stl",
        default=str(missing / "stls" / "0.stl"),
        help="CAD ID reference only; never compared with the TIFF",
    )
    parser.add_argument(
        "--tiff",
        default=str(
            missing
            / "tif_stacks"
            / "210127_Brian_Tran_strut_lattices_0point5dash1 1 Slices.tif"
        ),
    )
    parser.add_argument("--design-json", default=str(missing / "octet_truss_9x9x9.json"))
    parser.add_argument(
        "--registered-json",
        default=str(
            missing
            / "registered_jsons"
            / "210127_Brian_Tran_strut_lattices_0point5dash1 1 Slices.json"
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=str(output_path("stl_tiff_strut_errors")),
    )
    parser.add_argument(
        "--thresholds", nargs=3, type=float, default=(38557.0, 40054.0, 41018.0)
    )
    parser.add_argument(
        "--mm-per-design-unit",
        type=float,
        default=2.28,
        help="physical graph scale; paper cell edge 4.56 mm spans two graph units",
    )
    parser.add_argument(
        "--nominal-strut-diameter-mm",
        type=float,
        default=0.424,
        help="paper nominal diameter, used to validate STL outer surface extents",
    )
    parser.add_argument("--distance-tolerance-voxels", type=float, default=2.0)
    parser.add_argument("--endpoint-exclusion-fraction", type=float, default=0.10)
    parser.add_argument("--minimum-supported-bin-fraction", type=float, default=0.20)
    parser.add_argument("--minimum-gap-voxels", type=int, default=3)
    parser.add_argument("--minimum-realized-fraction", type=float, default=0.80)
    parser.add_argument("--minimum-perturbation-agreement", type=float, default=0.80)
    parser.add_argument(
        "--minimum-local-contrast-fraction",
        type=float,
        default=0.25,
        help=(
            "review-only veto for absolute-threshold errors when continuous "
            "annular/hysteresis contrast remains; must lie in (0, 1]"
        ),
    )
    parser.add_argument(
        "--disable-local-contrast-review",
        action="store_true",
        help="disable the conservative subthreshold error-to-review safeguard",
    )
    parser.add_argument("--limit-struts", type=int, default=None, help="smoke-test prefix only")
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--maximum-rss-gib", type=float, default=2.5)
    parser.add_argument("--checkpoint-every", type=int, default=500)
    parser.add_argument("--no-checkpoint", action="store_true")
    arguments = parser.parse_args(argv)
    if arguments.limit_struts is not None and arguments.limit_struts < 1:
        parser.error("--limit-struts must be positive")
    if arguments.workers < 1:
        parser.error("--workers must be positive")
    if arguments.maximum_rss_gib <= 0:
        parser.error("--maximum-rss-gib must be positive")
    if arguments.mm_per_design_unit <= 0:
        parser.error("--mm-per-design-unit must be positive")
    if arguments.nominal_strut_diameter_mm <= 0:
        parser.error("--nominal-strut-diameter-mm must be positive")
    if arguments.checkpoint_every < 1:
        parser.error("--checkpoint-every must be positive")
    if not 0.0 < arguments.minimum_local_contrast_fraction <= 1.0:
        parser.error("--minimum-local-contrast-fraction must lie in (0, 1]")
    return arguments


def _write_candidate_csv(directory: Path, payload: dict) -> Path:
    fields = (
        "strut_id",
        "edge_id",
        "junction0",
        "junction1",
        "endpoint0_xyz_voxel",
        "endpoint1_xyz_voxel",
        "has_error",
        "review_required",
        "confidence",
        "realized_axial_fraction",
        "longest_unrealized_gap_voxels",
        "bridge_connected_26",
        "stl_to_ct_near_fraction",
        "decision_reason",
    )
    rows = []
    for strut in payload["struts"]:
        if strut.get("has_error") is not True:
            continue
        rows.append({
            "strut_id": strut["id"],
            "edge_id": strut["edge_id"],
            "junction0": strut["junction0"],
            "junction1": strut["junction1"],
            "endpoint0_xyz_voxel": strut["endpoint0_xyz_voxel"],
            "endpoint1_xyz_voxel": strut["endpoint1_xyz_voxel"],
            "has_error": strut.get("has_error"),
            "review_required": strut.get("review_required"),
            "confidence": strut.get("confidence"),
            "realized_axial_fraction": strut.get("realized_axial_fraction"),
            "longest_unrealized_gap_voxels": strut.get("longest_unrealized_gap_voxels"),
            "bridge_connected_26": strut.get("bridge_connected_26"),
            "stl_to_ct_near_fraction": strut.get("stl_to_ct_near_fraction"),
            "decision_reason": strut.get("decision_reason"),
        })
    destination = directory / "error_candidates.csv"
    return write_csv(destination, rows, fields, create_parents=True)


def _write_review_csv(directory: Path, payload: dict) -> Path:
    """Write every applicable null/review case so vetoes cannot disappear."""

    fields = (
        "strut_id",
        "edge_id",
        "junction0",
        "junction1",
        "endpoint0_xyz_voxel",
        "endpoint1_xyz_voxel",
        "has_error",
        "review_required",
        "absolute_threshold_has_error",
        "realized_axial_fraction",
        "longest_unrealized_gap_voxels",
        "contrast_review_authorized",
        "contrast_shift_agreement",
        "decision_reason",
        "absolute_threshold_decision_reason",
    )
    rows = []
    for strut in payload["struts"]:
        if not (
            strut.get("comparison_applicable") is True
            and strut.get("has_error") is None
            and strut.get("review_required") is True
        ):
            continue
        rows.append({key: strut.get(key) for key in fields})
        rows[-1]["strut_id"] = strut["id"]
        rows[-1]["edge_id"] = strut["edge_id"]
        rows[-1]["junction0"] = strut["junction0"]
        rows[-1]["junction1"] = strut["junction1"]
        rows[-1]["endpoint0_xyz_voxel"] = strut["endpoint0_xyz_voxel"]
        rows[-1]["endpoint1_xyz_voxel"] = strut["endpoint1_xyz_voxel"]
    destination = directory / "review_candidates.csv"
    return write_csv(destination, rows, fields, create_parents=True)


def _write_summary(directory: Path, payload: dict) -> tuple[Path, Path]:
    comparison = payload["_comparison"]
    summary = comparison["summary"]
    json_path = write_json(directory / "summary.json", comparison, create_parents=True)
    lines = [
        "# Direct STL-to-TIFF strut comparison",
        "",
        "`0.5.stl` is the expected geometry and the raw TIFF is the observed material.",
        "The registered JSON supplies only stable strut IDs and CT-frame endpoints.",
        "",
        "## Counts",
        "",
        f"- Total source struts: {summary['strut_count']:,}",
        f"- Processed in this run: {summary['processed_count']:,}",
        f"- Not processed (smoke runs only): {summary['not_processed_count']:,}",
        f"- Automatically supported error candidates: {summary['error_candidate_count']:,}",
        f"- Stable healthy matches: {summary['healthy_count']:,}",
        f"- Undecided/review-required: {summary['undecided_count']:,}",
        f"- Not applicable (CAD-absent or skin-unobservable): {summary['not_applicable_count']:,}",
        f"- Intentionally absent in 0.5 STL: {summary['stl_intentionally_absent_count']:,}",
        "",
        "## Interpretation",
        "",
        "- `has_error: true` is a candidate requiring scientific review, not a confirmed subtype.",
        "- `has_error: null` means review-required uncertainty or non-applicable geometry; inspect `comparison_applicable` and `review_required`.",
        "- Missing-versus-broken classification and 3D visualization are intentionally deferred.",
        "- `0.stl` was used only to map monolithic CAD surface locations to graph IDs.",
        "",
    ]
    markdown_path = directory / "summary.md"
    from Components.reporting import atomic_write_bytes

    atomic_write_bytes(markdown_path, "\n".join(lines).encode("utf-8"), create_parents=True)
    return json_path, markdown_path


def main(argv: list[str] | None = None) -> int:
    arguments = parse_args(argv)
    directory = Path(arguments.output_dir).expanduser().resolve()
    directory.mkdir(parents=True, exist_ok=True)
    suffix = "" if arguments.limit_struts is None else f"_smoke_{arguments.limit_struts}"
    output_json = directory / f"stl_tiff_strut_errors{suffix}.json"
    checkpoint = None if arguments.no_checkpoint else directory / f"checkpoint{suffix}.jsonl"
    payload = compare_stl_to_tiff_struts(
        arguments.stl,
        arguments.tiff,
        arguments.registered_json,
        arguments.design_json,
        arguments.complete_stl,
        output_json_path=output_json,
        checkpoint_jsonl_path=checkpoint,
        material_thresholds=arguments.thresholds,
        mm_per_design_unit=arguments.mm_per_design_unit,
        nominal_strut_diameter_mm=arguments.nominal_strut_diameter_mm,
        distance_tolerance_voxels=arguments.distance_tolerance_voxels,
        endpoint_exclusion_fraction=arguments.endpoint_exclusion_fraction,
        minimum_supported_bin_fraction=arguments.minimum_supported_bin_fraction,
        minimum_gap_voxels=arguments.minimum_gap_voxels,
        minimum_realized_fraction=arguments.minimum_realized_fraction,
        minimum_perturbation_agreement=arguments.minimum_perturbation_agreement,
        minimum_local_contrast_fraction=(
            None
            if arguments.disable_local_contrast_review
            else arguments.minimum_local_contrast_fraction
        ),
        limit_struts=arguments.limit_struts,
        workers=arguments.workers,
        maximum_rss_bytes=int(arguments.maximum_rss_gib * 1024 ** 3),
        checkpoint_every=arguments.checkpoint_every,
    )
    if arguments.limit_struts is None:
        candidate_csv = _write_candidate_csv(directory, payload)
        review_csv = _write_review_csv(directory, payload)
        summary_json, summary_markdown = _write_summary(directory, payload)
        print(f"wrote {candidate_csv}")
        print(f"wrote {review_csv}")
        print(f"wrote {summary_json}")
        print(f"wrote {summary_markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
