"""Export STL-to-TIFF strut candidates as colored MeshLab PLY models."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import tempfile
from typing import Any, Sequence

import numpy as np


VERTEX_DTYPE = np.dtype([
    ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
    ("red", "u1"), ("green", "u1"), ("blue", "u1"),
])
FACE_DTYPE = np.dtype([("count", "u1"), ("indices", "<u4", (3,))])


def _xyz(value: Sequence[float], name: str) -> np.ndarray:
    result = np.asarray(value, dtype=np.float64)
    if result.shape != (3,) or not np.isfinite(result).all():
        raise ValueError(f"{name} must contain three finite XYZ values")
    return result


def cylinder_mesh(
    endpoint0_xyz: Sequence[float],
    endpoint1_xyz: Sequence[float],
    radius: float,
    *,
    segments: int = 8,
) -> tuple[np.ndarray, np.ndarray]:
    """Return capped cylinder vertices and triangular faces between two points."""

    first = _xyz(endpoint0_xyz, "endpoint0_xyz")
    second = _xyz(endpoint1_xyz, "endpoint1_xyz")
    if not np.isfinite(radius) or radius <= 0.0:
        raise ValueError("radius must be finite and positive")
    if not isinstance(segments, int) or segments < 6:
        raise ValueError("segments must be an integer >= 6")
    direction = second - first
    length = float(np.linalg.norm(direction))
    if length <= np.finfo(np.float64).eps:
        raise ValueError("cylinder endpoints must be distinct")
    direction /= length
    reference = np.zeros(3, dtype=np.float64)
    reference[int(np.argmin(np.abs(direction)))] = 1.0
    axis_u = np.cross(direction, reference)
    axis_u /= np.linalg.norm(axis_u)
    axis_v = np.cross(direction, axis_u)
    angles = np.linspace(0.0, 2.0 * np.pi, segments, endpoint=False)
    ring = radius * (
        np.cos(angles)[:, None] * axis_u[None, :]
        + np.sin(angles)[:, None] * axis_v[None, :]
    )
    vertices = np.vstack((first + ring, second + ring, first, second)).astype(np.float32)
    faces: list[tuple[int, int, int]] = []
    lower_center, upper_center = 2 * segments, 2 * segments + 1
    for index in range(segments):
        following = (index + 1) % segments
        faces.extend((
            (index, following, segments + index),
            (following, segments + following, segments + index),
            (lower_center, following, index),
            (upper_center, segments + index, segments + following),
        ))
    return vertices, np.asarray(faces, dtype=np.uint32)


def assemble_tubes(
    records: Sequence[dict[str, Any]],
    *,
    radius: float,
    color_rgb: tuple[int, int, int],
    segments: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Assemble equal-style strut records into one indexed colored mesh."""

    if any(not 0 <= int(value) <= 255 for value in color_rgb) or len(color_rgb) != 3:
        raise ValueError("color_rgb must contain three values in [0, 255]")
    vertex_chunks, face_chunks = [], []
    offset = 0
    for record in records:
        vertices, faces = cylinder_mesh(
            record["endpoint0_xyz_voxel"], record["endpoint1_xyz_voxel"],
            radius, segments=segments,
        )
        colored = np.empty(len(vertices), dtype=VERTEX_DTYPE)
        colored["x"], colored["y"], colored["z"] = vertices.T
        colored["red"], colored["green"], colored["blue"] = color_rgb
        vertex_chunks.append(colored)
        face_chunks.append(faces + offset)
        offset += len(vertices)
    if not vertex_chunks:
        return np.empty(0, dtype=VERTEX_DTYPE), np.empty((0, 3), dtype=np.uint32)
    return np.concatenate(vertex_chunks), np.concatenate(face_chunks)


def write_colored_mesh_ply(
    path: str | Path,
    vertices: np.ndarray,
    faces: np.ndarray,
    *,
    comments: Sequence[str] = (),
) -> Path:
    """Atomically write binary little-endian PLY with vertex RGB colors."""

    vertices = np.asarray(vertices)
    faces = np.asarray(faces, dtype=np.uint32)
    if vertices.ndim != 1 or vertices.dtype != VERTEX_DTYPE:
        raise ValueError("vertices must be a one-dimensional VERTEX_DTYPE array")
    if faces.ndim != 2 or faces.shape[1:] != (3,):
        raise ValueError("faces must have shape (N, 3)")
    if faces.size and int(faces.max()) >= len(vertices):
        raise ValueError("face references a nonexistent vertex")
    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    clean = [str(value).replace("\n", " ").replace("\r", " ") for value in comments]
    header = "\n".join([
        "ply", "format binary_little_endian 1.0",
        "comment generated by Aman_Scripts/export_candidate_struts.py",
        *(f"comment {value}" for value in clean),
        f"element vertex {len(vertices)}",
        "property float x", "property float y", "property float z",
        "property uchar red", "property uchar green", "property uchar blue",
        f"element face {len(faces)}", "property list uchar uint vertex_indices",
        "end_header", "",
    ]).encode("ascii")
    face_records = np.empty(len(faces), dtype=FACE_DTYPE)
    face_records["count"] = 3
    face_records["indices"] = faces
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb", dir=destination.parent, prefix=f".{destination.name}.",
            suffix=".tmp", delete=False,
        ) as handle:
            temporary_name = handle.name
            handle.write(header)
            handle.write(np.ascontiguousarray(vertices).tobytes())
            handle.write(face_records.tobytes())
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, destination)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)
    return destination


def select_records(payload: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    struts = payload.get("struts")
    if not isinstance(struts, list):
        raise ValueError("comparison JSON must contain a struts list")
    expected = [record for record in struts if record.get("stl_expected_present") is True]
    candidates = [record for record in expected if record.get("has_error") is True]
    if not expected or not candidates:
        raise ValueError("comparison JSON must contain expected struts and candidates")
    return expected, candidates


def _candidate_manifest(records: Sequence[dict[str, Any]]) -> dict[str, Any]:
    fields = (
        "id", "edge_id", "endpoint0_xyz_voxel", "endpoint1_xyz_voxel",
        "observed_axial_fraction", "longest_unsupported_gap_voxels",
        "connected_support", "failed_checks", "decision_reason",
    )
    rows = [{field: record.get(field) for field in fields} for record in records]
    rows.sort(key=lambda row: (-float(row["longest_unsupported_gap_voxels"] or 0.0), row["id"]))
    return {
        "meaning": "red tube is the STL-expected corridor flagged by raw-TIFF evidence",
        "candidate_count": len(rows),
        "coordinate_frame": "native CT XYZ voxel coordinates",
        "candidates": rows,
    }


def export_models(
    comparison_json: str | Path,
    output_directory: str | Path,
    *,
    reference_radius: float = 0.18,
    candidate_radius: float = 1.10,
    segments: int = 8,
) -> dict[str, Any]:
    source = Path(comparison_json).expanduser().resolve(strict=True)
    destination = Path(output_directory).expanduser().resolve()
    with source.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    expected, candidates = select_records(payload)
    reference_vertices, reference_faces = assemble_tubes(
        expected, radius=reference_radius, color_rgb=(70, 130, 180), segments=segments,
    )
    candidate_vertices, candidate_faces = assemble_tubes(
        candidates, radius=candidate_radius, color_rgb=(255, 35, 35), segments=segments,
    )
    candidate_only = write_colored_mesh_ply(
        destination / "candidate_struts_red.ply", candidate_vertices, candidate_faces,
        comments=(f"{len(candidates)} TIFF-derived candidate corridors", "red = review candidate"),
    )
    combined_vertices = np.concatenate((reference_vertices, candidate_vertices))
    combined_faces = np.concatenate((reference_faces, candidate_faces + len(reference_vertices)))
    combined = write_colored_mesh_ply(
        destination / "lattice_blue_candidates_red.ply", combined_vertices, combined_faces,
        comments=(
            f"{len(expected)} STL-expected struts in blue",
            f"{len(candidates)} TIFF-derived candidate corridors overlaid in red",
        ),
    )
    manifest = _candidate_manifest(candidates)
    manifest_path = destination / "candidate_struts.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    readme = destination / "README.md"
    readme.write_text(
        "# MeshLab strut-candidate visualization\n\n"
        "Open `lattice_blue_candidates_red.ply` for full context. Thin blue tubes are "
        "STL-expected struts; thick red tubes are locations where the raw TIFF comparison "
        "produced `has_error=true`. Open `candidate_struts_red.ply` to see only candidates.\n\n"
        "The red tube marks where CAD material was expected. It is not CT-reconstructed "
        "material and does not distinguish missing from broken. Candidate IDs and metrics "
        "are in `candidate_struts.json`. Coordinates are native CT XYZ voxels.\n",
        encoding="utf-8",
    )
    return {
        "expected_count": len(expected), "candidate_count": len(candidates),
        "combined_ply": str(combined), "candidate_ply": str(candidate_only),
        "manifest": str(manifest_path), "readme": str(readme),
        "combined_vertex_count": len(combined_vertices),
        "combined_face_count": len(combined_faces),
    }


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--comparison-json",
        default="Aman_Scripts/outputs/simple_strut_metrology/strut_metrology.json",
    )
    parser.add_argument(
        "--output-dir",
        default="Aman_Scripts/outputs/simple_strut_metrology/meshlab_candidates",
    )
    parser.add_argument("--reference-radius", type=float, default=0.18)
    parser.add_argument("--candidate-radius", type=float, default=1.10)
    parser.add_argument("--segments", type=int, default=8)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    arguments = parse_args(argv)
    result = export_models(
        arguments.comparison_json, arguments.output_dir,
        reference_radius=arguments.reference_radius,
        candidate_radius=arguments.candidate_radius,
        segments=arguments.segments,
    )
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
